extends:
  - airbnb-base
  - prettier
env:
  node: true
  browser: true
  es6: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false


overrides:
  - files:
    - '*.ts'
    parser: '@typescript-eslint/parser'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    parserOptions:
      project:
        - ./tsconfig.json
    rules:
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-argument': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-non-null-assertion': off
      '@typescript-eslint/no-unused-vars': error

settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

rules:
  eqeqeq:
    - error
    - smart
  prefer-const:
    - error
    - destructuring : all
  import/extensions:
    - error
    - never
  no-plusplus: off
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  no-use-before-define:
    - error
    - functions: false
  no-void:
    - error
    - allowAsStatement: true
